name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref_name }}'
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.event.pull_request.merged == true
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'
      - name: Tag
        if: github.event.pull_request.merged == true
        uses: anothrNick/github-tag-action@1.62.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: logx-go
          WITH_V: true

